# Алиасы для git команд.
alias git_last_commit='git --no-pager log -n 1 --pretty=format:"%h%x09%an%x09%ad%x09%s" --date=format:"%Y-%m-%d %H:%M:%S"'
alias git_last_commit_pretty='echo "" &&  echo "Last commit:" && git_last_commit && echo "" && echo ""'
alias gst="git status && git_last_commit_pretty"
alias gd="git diff -M"
alias gds="gd --staged"
alias ga="git add"
alias gaa="git add --all"
alias gl="git log"
alias gs="git show"
alias gci="git commit --verbose"
alias gco="git checkout && git_last_commit_pretty"
alias gru="git remote update"
alias gcp="git cherry-pick -x"
alias grst="git reset"
alias grstfull="grst --hard && git clean -fd && gst"
alias gbg="git branch -a | grep"

# Так как в MacOS сломался мой любимый grext, попробую перейти на алиасы для grep.
alias grep_all="grep -irn --exclude-dir .git --exclude-dir .idea"
alias grep_js="grep --include \"*.js\""
alias grecss="grep --include \"*.css\""
alias grep_html="grep --include \"*.html\""
alias grep_ts="grep -ir --include \"*.ts\""

# Для ok-admin исключаю скомпилированные шаблоны, чтобы они не забивали выдачу.
# FIXME!!!
alias grejs="grep_js --exclude populate_template_cache.js"
alias grehtml="grep_html --exclude populate_template_cache.js"
alias greee="grep_all --exclude populate_template_cache.js"
alias grets="grep_ts --exclude populate_template_cache.js"

# OK aliases
alias ant-deploy-dev="echo 'Use ant-dd or ant-dd-pl instead!'"
alias ant-dd="ant clean refresh-cache build deploy-dev"
alias ant-ddpl="ant clean refresh-cache build deploy-dev ivy-publish-local"
alias ant-rt="ant clean run-tomcat"
