scriptencoding utf-8
set encoding=utf-8
set fileencoding=utf-8

" pathogen init
filetype off
execute pathogen#infect()
execute pathogen#helptags()

syntax on
filetype on
filetype plugin on
" filetype plugin indent on " пока удалим это, а то в js'е vim делает какие-то неприятные отступы

" Чиним автодополнение.
set omnifunc=syntaxcomplete#Complete

" включение режима 256 цветов до переключения цветовой схемы
set t_Co=256
" включаем цветовую схему
set background=light
colorscheme myhemisu

set textwidth=120 " Автоперенос текста.
set laststatus=2 "Всегда показывать строку состояния
set number "Нумеровать строки
set numberwidth=4 "Ширина поля нумерации строк
set ruler "Всегда показывать позицию курсора
set title "Установить имя текущего файла и путь к нему в заголовке
set list "Включить подсветку табуляции и пробелов в конце строки
set listchars=tab:>·,trail:· "Установить символы которыми будет осуществляться подсветка
set hlsearch "Подсветка результатов поиска
set nowrapscan "Останавливать поиск по достижению конца файла
set tabstop=4 "Размер табуляции
set shiftwidth=4 "Размер отступов
set smartindent "Умные отступы
set autoindent "Автоматические отступы
set foldcolumn=1 "Отступ между кодом и левой границей
set smartcase "Умный поиск (?)
set ignorecase "Включаем регистронезависимый поиск
set incsearch " Поиск одновременно с вводом.
set completeopt=longest,menuone
set scrolloff=5 " Отступ курсора от конца экрана

" Отступы в 2 пробела для Angular.
set tabstop=2 "Размер табуляции
set shiftwidth=2 "Размер отступов
set smartindent "Умные отступы
" set expandtab

" Убираю обычный индикатор режима потому, что использую vim-airline.
set noshowmode

highlight ColorColumn ctermbg=253
let &colorcolumn="100,".join(range(120,999), ",")

set splitright " Открываем вертикальные окна справа.

" Возвращаем нормальную функциональность backspace в vim 7.4.
set backspace=2

" NERDTree
" отображение скрытых файлов
let NERDTreeShowHidden=1
let NERDTreeAutoDeleteBuffer = 1

" скрытие ненужных сообщений
set shortmess=atI
" подсвечивать строку с курсором
set cursorline
" отключить бекап файлов
set nobackup
set noswapfile
set nowritebackup

" не сохраняем настройки в сессию - пусть всегда берутся из конфига
set sessionoptions-=options
" сохраняем изменения в размерах окон, чтобы не раздражало в будущем
set sessionoptions+=resize

" Папка для backup-файлов, // означает автоматическое разрешение конфликтов имён
set backupdir=~/.vim/_backup//
" Папка для swp-файлов, // означает автоматическое разрешение конфликтов имён
set directory=~/.vim/_swp//

" json, jake как javascript
au BufNewFile,BufRead *.json set filetype=javascript
au BufNewFile,BufRead *.tjson set filetype=javascript
au BufNewFile,BufRead *.jake set filetype=javascript
au BufNewFile,BufRead Jakefile set filetype=javascript
au BufNewFile,BufRead *.bemhtml set filetype=javascript

" быстрое сохранение сессии/файлов и выход
function! SaveSessionAndQuit()
	!rm -f ~/.session.vim
	mksession ~/.session.vim
	wa
	qa
endfunction

" Запуск NERDTree первым табом.
function! OpenNerdTree()
	" У меня не получилось перенести NERDTree из окна в таб, поэтому
	" действуем через пустой таб, где будет закрыто пустое соседнее окно.
	:tabnew
	:NERDTree
	:wincmd l
	:q
	:tabm 0
endfunction


" Запуск NERDTree при старте vim'а - переход на таб с целевым файлом.
function! OpenNerdTreeAtStart()
	:call OpenNerdTree()
	" Возвращаемся на таб с целевым файлом.
	:tabnext
	" Если таб пустой, то закрываем его.
	let $currFile = @%
	if $currFile == ""
		:q
	endif
	" Если мы набираем комментарий к коммиту git'а, то закрываем NERDTree.
	if expand("%:t") == "COMMIT_EDITMSG"
		:tabNext
		:q
	endif
endfunction


" Проверяем, существует ли файл по заданному пути.
" http://stackoverflow.com/questions/3098521/vimscript-how-to-detect-if-specific-file-exists
function! CheckFileExists(fileName)
	if filereadable(a:fileName)
		return 1
	else
		return 0
	endif
endfunction


" Открыть файл под курсором.
function! OpenFileUnderCursor()
	" Получаем имя файла под курсором
	let $path = expand('<cfile>')

	" Открываем таб с файлом
	if $path == ""
		echo "No file name under your cursor!"
	elseif CheckFileExists($path) == 0
		echo "File " . $path . " not found!"
	else
		:tabnew $path
	endif
endfunction

function! UseLeaderHotkey(afterLeader)
	echo "Current hotkey is deprecated! Please, use '\<Leader\>" . a:afterLeader . "' hotkey."
endfunction


" Горячие клавиши:

" быстрое открытие файлов в табе
map <F1> :call UseLeaderHotkey("1")<CR>
noremap <Leader>1 :tabnew<Space>
noremap <Leader>o :tabnew<Space>
" очистка поиска
map <F2> :call UseLeaderHotkey("2")<CR>
noremap <Leader>2 :let @/=''<CR>
" сохранение изменений
map <F3> :call UseLeaderHotkey("3")<CR>
imap <F3> :call UseLeaderHotkey("3")<CR>
noremap <Leader>3 :update<CR>
inoremap <Leader>3 <Esc>:update<CR>a
noremap <Leader>w :update<CR>
inoremap <Leader>w <Esc>:update<CR>a
" сохранение изменений из insert-режима с сохранением позиции курсора
" открыть файл под курсором
map <F4> :call UseLeaderHotkey("4")<CR>
noremap <Leader>4 :call OpenFileUnderCursor()<CR>
" закрытие текущего таба
map <F5> :q<CR>
noremap <Leader>5 :q<CR>
noremap <Leader>q :q<CR>
" вертикальный сплит файла
map <F6> :call UseLeaderHotkey("6")<CR>
noremap <Leader>6 :vsplit<Space>
" выход с сохранением сессии
map <F11> :call UseLeaderHotkey("9")<CR>
map <Leader>9 :call SaveSessionAndQuit()
" быстрый переход между табами
map <C-h> gT
map <C-l> gt

imap <Leader>; <Esc>A;<Esc>

" Настройки Ctrl-P
let g:ctrlp_use_caching = 0
let g:ctrlp_max_height = 30
let g:ctrlp_open_multiple_files = 'tj'
let g:ctrlp_lazy_update = 1
let g:ctrlp_custom_ignore = {
	\ 'dir': '\v[\/](node_modules|bower_components)$',
	\ }
let g:ctrlp_prompt_mappings = {
	\ 'AcceptSelection("e")': [],
	\ 'AcceptSelection("t")': ['<c-t>', '<cr>'],
	\ 'MarkToOpen()': ['<c-z>', '<space>'],
	\ }

" быстрые скачки на несколько строк
map J 5j
map K 5k
" быстрые скачки на несколько слов в стороны
map H 3b
map L 3e

" Автозапуски.
autocmd vimenter * call OpenNerdTreeAtStart()

" Отключаем стирание регистра при вставке через _p_.
" http://vim.wikia.com/wiki/Replace_a_word_with_yanked_text
xnoremap p "_dP

" Перенос закрывающей фигурной скобки на новую строку.
" http://stackoverflow.com/questions/21316727/automatic-closing-brackets-for-vim
let g:delimitMate_expand_cr = 2
